name: Deploy to GitHub Pages
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: "20"
                cache: "npm"
                working-directory: ./salary-calc

            - name: Install Dependencies
              run: "npm ci"
              working-directory: ./salary-calc

            - name: Build Project
              run: npx --no-install npm run build
              working-directory: ./salary-calc

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                path: ./salary-calc/build

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: ./salary-calc
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v3
